/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DidManagerInterface extends Interface {
  getFunction(
    nameOrSignature: "addController" | "createDid" | "createVM" | "validateVM"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DidCreated" | "VMCreated" | "VMValidated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addController",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createDid",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createVM",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      [BytesLike, BytesLike],
      BytesLike[],
      [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike],
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "validateVM",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "addController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createDid", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createVM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "validateVM", data: BytesLike): Result;
}

export namespace DidCreatedEvent {
  export type InputTuple = [idHash: BytesLike, creator: AddressLike];
  export type OutputTuple = [idHash: string, creator: string];
  export interface OutputObject {
    idHash: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VMCreatedEvent {
  export type InputTuple = [
    didIdHash: BytesLike,
    id: BytesLike,
    vmIdHash: BytesLike,
    positionHash: BytesLike
  ];
  export type OutputTuple = [
    didIdHash: string,
    id: string,
    vmIdHash: string,
    positionHash: string
  ];
  export interface OutputObject {
    didIdHash: string;
    id: string;
    vmIdHash: string;
    positionHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VMValidatedEvent {
  export type InputTuple = [id: BytesLike];
  export type OutputTuple = [id: string];
  export interface OutputObject {
    id: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DidManager extends BaseContract {
  connect(runner?: ContractRunner | null): DidManager;
  waitForDeployment(): Promise<this>;

  interface: DidManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addController: TypedContractMethod<
    [
      method0: BytesLike,
      method1: BytesLike,
      method2: BytesLike,
      id: BytesLike,
      vmId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  createDid: TypedContractMethod<
    [
      method0: BytesLike,
      method1: BytesLike,
      method2: BytesLike,
      random: BytesLike,
      vmId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  createVM: TypedContractMethod<
    [
      method0: BytesLike,
      method1: BytesLike,
      method2: BytesLike,
      id: BytesLike,
      vmId: BytesLike,
      type_: [BytesLike, BytesLike],
      publicKey: BytesLike[],
      blockchainAccountId: [
        BytesLike,
        BytesLike,
        BytesLike,
        BytesLike,
        BytesLike
      ],
      thisBCAddress: AddressLike,
      expiration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  validateVM: TypedContractMethod<
    [positionHash: BytesLike, expiration: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addController"
  ): TypedContractMethod<
    [
      method0: BytesLike,
      method1: BytesLike,
      method2: BytesLike,
      id: BytesLike,
      vmId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createDid"
  ): TypedContractMethod<
    [
      method0: BytesLike,
      method1: BytesLike,
      method2: BytesLike,
      random: BytesLike,
      vmId: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createVM"
  ): TypedContractMethod<
    [
      method0: BytesLike,
      method1: BytesLike,
      method2: BytesLike,
      id: BytesLike,
      vmId: BytesLike,
      type_: [BytesLike, BytesLike],
      publicKey: BytesLike[],
      blockchainAccountId: [
        BytesLike,
        BytesLike,
        BytesLike,
        BytesLike,
        BytesLike
      ],
      thisBCAddress: AddressLike,
      expiration: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateVM"
  ): TypedContractMethod<
    [positionHash: BytesLike, expiration: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DidCreated"
  ): TypedContractEvent<
    DidCreatedEvent.InputTuple,
    DidCreatedEvent.OutputTuple,
    DidCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VMCreated"
  ): TypedContractEvent<
    VMCreatedEvent.InputTuple,
    VMCreatedEvent.OutputTuple,
    VMCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VMValidated"
  ): TypedContractEvent<
    VMValidatedEvent.InputTuple,
    VMValidatedEvent.OutputTuple,
    VMValidatedEvent.OutputObject
  >;

  filters: {
    "DidCreated(bytes32,address)": TypedContractEvent<
      DidCreatedEvent.InputTuple,
      DidCreatedEvent.OutputTuple,
      DidCreatedEvent.OutputObject
    >;
    DidCreated: TypedContractEvent<
      DidCreatedEvent.InputTuple,
      DidCreatedEvent.OutputTuple,
      DidCreatedEvent.OutputObject
    >;

    "VMCreated(bytes32,bytes32,bytes32,bytes32)": TypedContractEvent<
      VMCreatedEvent.InputTuple,
      VMCreatedEvent.OutputTuple,
      VMCreatedEvent.OutputObject
    >;
    VMCreated: TypedContractEvent<
      VMCreatedEvent.InputTuple,
      VMCreatedEvent.OutputTuple,
      VMCreatedEvent.OutputObject
    >;

    "VMValidated(bytes32)": TypedContractEvent<
      VMValidatedEvent.InputTuple,
      VMValidatedEvent.OutputTuple,
      VMValidatedEvent.OutputObject
    >;
    VMValidated: TypedContractEvent<
      VMValidatedEvent.InputTuple,
      VMValidatedEvent.OutputTuple,
      VMValidatedEvent.OutputObject
    >;
  };
}
