/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { Create2Deployable } from "./Create2Deployable";
export type { DidManager } from "./DidManager";
export type { Storage } from "./Storage";
export type { StorageUpgr } from "./StorageUpgr";
export type { StorageUpgrV1 } from "./StorageUpgrV1";
export type { VMStorage } from "./VMStorage";
