/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICodeTrust,
  ICodeTrustInterface,
} from "../../../../decentralized-code-trust/contracts/interfaces/ICodeTrust";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "trustedCode",
        type: "address",
      },
      {
        internalType: "address",
        name: "by",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "extTimestamp",
        type: "uint256",
      },
    ],
    name: "isTrustedCode",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "trustedCode",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "duration",
        type: "uint256",
      },
    ],
    name: "trustCodeAt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "trustedCode",
        type: "address",
      },
    ],
    name: "untrustCodeAt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ICodeTrust__factory {
  static readonly abi = _abi;
  static createInterface(): ICodeTrustInterface {
    return new Interface(_abi) as ICodeTrustInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ICodeTrust {
    return new Contract(address, _abi, runner) as unknown as ICodeTrust;
  }
}
