/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IDidManagerInterface extends Interface {
  getFunction(nameOrSignature: "createDid"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DidCreated"): EventFragment;

  encodeFunctionData(
    functionFragment: "createDid",
    values: [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "createDid", data: BytesLike): Result;
}

export namespace DidCreatedEvent {
  export type InputTuple = [id: BytesLike, creator: AddressLike];
  export type OutputTuple = [id: string, creator: string];
  export interface OutputObject {
    id: string;
    creator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDidManager extends BaseContract {
  connect(runner?: ContractRunner | null): IDidManager;
  waitForDeployment(): Promise<this>;

  interface: IDidManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createDid: TypedContractMethod<
    [
      random: BytesLike,
      method0: BytesLike,
      method1: BytesLike,
      method2: BytesLike,
      vmId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createDid"
  ): TypedContractMethod<
    [
      random: BytesLike,
      method0: BytesLike,
      method1: BytesLike,
      method2: BytesLike,
      vmId: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DidCreated"
  ): TypedContractEvent<
    DidCreatedEvent.InputTuple,
    DidCreatedEvent.OutputTuple,
    DidCreatedEvent.OutputObject
  >;

  filters: {
    "DidCreated(bytes32,address)": TypedContractEvent<
      DidCreatedEvent.InputTuple,
      DidCreatedEvent.OutputTuple,
      DidCreatedEvent.OutputObject
    >;
    DidCreated: TypedContractEvent<
      DidCreatedEvent.InputTuple,
      DidCreatedEvent.OutputTuple,
      DidCreatedEvent.OutputObject
    >;
  };
}
