/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDidManager } from "./IDidManager";
export type { IPayableOwner } from "./IPayableOwner";
export type { IStorage } from "./IStorage";
export type { IVMStorage } from "./IVMStorage";
