/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IVMStorageInterface extends Interface {
  getFunction(
    nameOrSignature: "createVM" | "initialize" | "validateVM"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "createVM",
    values: [
      BytesLike,
      BytesLike,
      [BytesLike, BytesLike],
      BytesLike[],
      [BytesLike, BytesLike, BytesLike, BytesLike, BytesLike],
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "validateVM",
    values: [BytesLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "createVM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "validateVM", data: BytesLike): Result;
}

export interface IVMStorage extends BaseContract {
  connect(runner?: ContractRunner | null): IVMStorage;
  waitForDeployment(): Promise<this>;

  interface: IVMStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createVM: TypedContractMethod<
    [
      didHash: BytesLike,
      id: BytesLike,
      type_: [BytesLike, BytesLike],
      publicKey: BytesLike[],
      blockchainAccountId: [
        BytesLike,
        BytesLike,
        BytesLike,
        BytesLike,
        BytesLike
      ],
      thisBCAddress: AddressLike,
      expiration: BigNumberish
    ],
    [[string, string] & { vmIdHash: string; positionHash: string }],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [codeTrust: AddressLike, didManager: AddressLike],
    [void],
    "nonpayable"
  >;

  validateVM: TypedContractMethod<
    [positionHash: BytesLike, expiration: BigNumberish, sender: AddressLike],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createVM"
  ): TypedContractMethod<
    [
      didHash: BytesLike,
      id: BytesLike,
      type_: [BytesLike, BytesLike],
      publicKey: BytesLike[],
      blockchainAccountId: [
        BytesLike,
        BytesLike,
        BytesLike,
        BytesLike,
        BytesLike
      ],
      thisBCAddress: AddressLike,
      expiration: BigNumberish
    ],
    [[string, string] & { vmIdHash: string; positionHash: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [codeTrust: AddressLike, didManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "validateVM"
  ): TypedContractMethod<
    [positionHash: BytesLike, expiration: BigNumberish, sender: AddressLike],
    [string],
    "nonpayable"
  >;

  filters: {};
}
