/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  Create2Deployable,
  Create2DeployableInterface,
} from "../../contracts/Create2Deployable";

const _abi = [
  {
    inputs: [],
    name: "Create2EmptyBytecode",
    type: "error",
  },
  {
    inputs: [],
    name: "Create2FailedDeployment",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "balance",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "needed",
        type: "uint256",
      },
    ],
    name: "Create2InsufficientBalance",
    type: "error",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "contractAddress",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "Deployed",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "bytecodeHash",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "deployer",
        type: "address",
      },
    ],
    name: "computeAddress",
    outputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "salt",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "bytecode",
        type: "bytes",
      },
    ],
    name: "deploy",
    outputs: [
      {
        internalType: "address",
        name: "addr",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102e9806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806366cfa0571461003b578063780653061461006a575b600080fd5b61004e6100493660046101ee565b61007d565b6040516001600160a01b03909116815260200160405180910390f35b61004e61007836600461026e565b610101565b60006100c0858585858080601f01602080910402602001604051908101604052809392919081815260200183838082843760009201919091525061013792505050565b60405190915033906001600160a01b038316907f09e48df7857bd0c1e0d31bb8a85d42cf1874817895f171c917f6ee2cea73ec2090600090a3949350505050565b60006001600160a01b0382166101225761011b84846101bb565b9050610130565b61012d8484846101c4565b90505b9392505050565b6000834710156101675760405163392efb2b60e21b81524760048201526024810185905260440160405180910390fd5b815160000361018957604051631328927760e21b815260040160405180910390fd5b8282516020840186f590506001600160a01b03811661013057604051633a0ba96160e11b815260040160405180910390fd5b60006101308383305b6000604051836040820152846020820152828152600b8101905060ff815360559020949350505050565b6000806000806060858703121561020457600080fd5b8435935060208501359250604085013567ffffffffffffffff8082111561022a57600080fd5b818701915087601f83011261023e57600080fd5b81358181111561024d57600080fd5b88602082850101111561025f57600080fd5b95989497505060200194505050565b60008060006060848603121561028357600080fd5b833592506020840135915060408401356001600160a01b03811681146102a857600080fd5b80915050925092509256fea264697066735822122031f8bf04c3ebc2a5d2653b56917d0a66e1a3267e2bc6a3cf129440d6ee0212e364736f6c63430008140033";

type Create2DeployableConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Create2DeployableConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Create2Deployable__factory extends ContractFactory {
  constructor(...args: Create2DeployableConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      Create2Deployable & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): Create2Deployable__factory {
    return super.connect(runner) as Create2Deployable__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Create2DeployableInterface {
    return new Interface(_abi) as Create2DeployableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Create2Deployable {
    return new Contract(address, _abi, runner) as unknown as Create2Deployable;
  }
}
