/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  DidManager,
  DidManagerInterface,
} from "../../contracts/DidManager";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IVMStorage",
        name: "vmStorage",
        type: "address",
      },
      {
        internalType: "contract IServiceStorage",
        name: "serviceStorage",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
    ],
    name: "DidCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "random",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "method0",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "method1",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "method2",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "vmId",
        type: "bytes32",
      },
    ],
    name: "createDid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516103a43803806103a483398101604081905261002f91610078565b600080546001600160a01b039384166001600160a01b031991821617909155600180549290931691161790556100b2565b6001600160a01b038116811461007557600080fd5b50565b6000806040838503121561008b57600080fd5b825161009681610060565b60208401519092506100a781610060565b809150509250929050565b6102e3806100c16000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063c2017b2d14610030575b600080fd5b61004361003e36600461024b565b610045565b005b8461008c5760405162461bcd60e51b8152602060048201526012602482015271052616e646f6d2063616e6e6f7420626520360741b60448201526064015b60405180910390fd5b8361009c5763363d383360e11b93505b826100ac576336b0b4b760e11b92505b816100b657600091505b806100c55750630766d2d360e41b5b60408051602081018690529081018490526060808201849052608082018790526bffffffffffffffffffffffff1933821b811660a08401524260b48401524190911b1660d4820152434060e88201526000906101080160408051601f1981840301815282825280516020918201209083018890529082018690526060820185905260808201819052915060009060a001604051602081830303815290604052805190602001209050610176816101ee565b6101af5760405162461bcd60e51b815260206004820152600a60248201526944494420696e2075736560b01b6044820152606401610083565b6101b88161022b565b604051339083907fc4e16972f67284004a0a3bc3498bface6e7c575ad245dc1267778ebe946f28a190600090a350505050505050565b6000818152600260205260408120544211806102165750600082815260026020526040902054155b1561022357506001919050565b506000919050565b610239630784ce0042610286565b60009182526002602052604090912055565b600080600080600060a0868803121561026357600080fd5b505083359560208501359550604085013594606081013594506080013592509050565b808201808211156102a757634e487b7160e01b600052601160045260246000fd5b9291505056fea2646970667358221220d5889b602894e4106b116f7da44562b8545fb81fdbdeb32cbb014c95ee0ad8da64736f6c63430008140033";

type DidManagerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DidManagerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DidManager__factory extends ContractFactory {
  constructor(...args: DidManagerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    vmStorage: AddressLike,
    serviceStorage: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(
      vmStorage,
      serviceStorage,
      overrides || {}
    );
  }
  override deploy(
    vmStorage: AddressLike,
    serviceStorage: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(vmStorage, serviceStorage, overrides || {}) as Promise<
      DidManager & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): DidManager__factory {
    return super.connect(runner) as DidManager__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DidManagerInterface {
    return new Interface(_abi) as DidManagerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): DidManager {
    return new Contract(address, _abi, runner) as unknown as DidManager;
  }
}
