/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  SimpleInitializable,
  SimpleInitializableInterface,
} from "../../contracts/SimpleInitializable";

const _abi = [
  {
    inputs: [],
    name: "isInitialized",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class SimpleInitializable__factory {
  static readonly abi = _abi;
  static createInterface(): SimpleInitializableInterface {
    return new Interface(_abi) as SimpleInitializableInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): SimpleInitializable {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as SimpleInitializable;
  }
}
