/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../../common";
import type { VMStorage, VMStorageInterface } from "../../contracts/VMStorage";

const _abi = [
  {
    inputs: [
      {
        internalType: "contract IDidManager",
        name: "didManager",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "didHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "type_",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "publicKey",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "blockchainAccountId",
        type: "bytes32",
      },
    ],
    name: "addVM",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516102f23803806102f283398101604081905261002f9161009b565b6000546040516349028bf360e11b81526001600160a01b038381166004830152600160248301529091169063920517e690604401600060405180830381600087803b15801561007d57600080fd5b505af1158015610091573d6000803e3d6000fd5b50505050506100cb565b6000602082840312156100ad57600080fd5b81516001600160a01b03811681146100c457600080fd5b9392505050565b610218806100da6000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80639f39d7eb14610030575b600080fd5b61004361003e36600461017a565b610045565b005b604080516080810182528581526020808201869052818301859052606082018490526000888152600382528381205484519283018a905260f81b6001600160f81b03191693820193909352909160019160410160408051808303601f190181529181528151602092830120835282820193909352908201600090812084518155848301516001820155848401516002808301919091556060958601516003928301558a83529083528382205484519384018b905293830189905260ff9093169390910160408051808303601f1901815291815281516020928301208352828201939093529082016000908120805460ff191660ff95861617905588815260039091529081208054909216919061015a836101b5565b91906101000a81548160ff021916908360ff160217905550505050505050565b600080600080600060a0868803121561019257600080fd5b505083359560208501359550604085013594606081013594506080013592509050565b600060ff821660ff81036101d957634e487b7160e01b600052601160045260246000fd5b6001019291505056fea2646970667358221220fbecad90c05707ce45d8013232066093a9da7396e71a951f9a7b5bb0710d72a564736f6c63430008140033";

type VMStorageConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: VMStorageConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class VMStorage__factory extends ContractFactory {
  constructor(...args: VMStorageConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    didManager: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(didManager, overrides || {});
  }
  override deploy(
    didManager: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(didManager, overrides || {}) as Promise<
      VMStorage & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): VMStorage__factory {
    return super.connect(runner) as VMStorage__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): VMStorageInterface {
    return new Interface(_abi) as VMStorageInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): VMStorage {
    return new Contract(address, _abi, runner) as unknown as VMStorage;
  }
}
