/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDidManager,
  IDidManagerInterface,
} from "../../../contracts/interfaces/IDidManager";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        indexed: true,
        internalType: "address",
        name: "creator",
        type: "address",
      },
    ],
    name: "DidCreated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "random",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "method0",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "method1",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "method2",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "vmId",
        type: "bytes32",
      },
    ],
    name: "createDid",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDidManager__factory {
  static readonly abi = _abi;
  static createInterface(): IDidManagerInterface {
    return new Interface(_abi) as IDidManagerInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDidManager {
    return new Contract(address, _abi, runner) as unknown as IDidManager;
  }
}
