/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVMStorage,
  IVMStorageInterface,
} from "../../../contracts/interfaces/IVMStorage";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "didHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
      {
        internalType: "bytes32[2]",
        name: "type_",
        type: "bytes32[2]",
      },
      {
        internalType: "bytes32[16]",
        name: "publicKey",
        type: "bytes32[16]",
      },
      {
        internalType: "bytes32[5]",
        name: "blockchainAccountId",
        type: "bytes32[5]",
      },
      {
        internalType: "address",
        name: "thisBCAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "expiration",
        type: "uint256",
      },
    ],
    name: "createVM",
    outputs: [
      {
        internalType: "bytes32",
        name: "vmIdHash",
        type: "bytes32",
      },
      {
        internalType: "bytes32",
        name: "positionHash",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "contract ICodeTrust",
        name: "codeTrust",
        type: "address",
      },
      {
        internalType: "contract IDidManager",
        name: "didManager",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "positionHash",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "expiration",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
    ],
    name: "validateVM",
    outputs: [
      {
        internalType: "bytes32",
        name: "id",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVMStorage__factory {
  static readonly abi = _abi;
  static createInterface(): IVMStorageInterface {
    return new Interface(_abi) as IVMStorageInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVMStorage {
    return new Contract(address, _abi, runner) as unknown as IVMStorage;
  }
}
