/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface ICodeTrustInterface extends Interface {
  getFunction(
    nameOrSignature: "isTrustedCode" | "trustCodeAt" | "untrustCodeAt"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isTrustedCode",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "trustCodeAt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "untrustCodeAt",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "isTrustedCode",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustCodeAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "untrustCodeAt",
    data: BytesLike
  ): Result;
}

export interface ICodeTrust extends BaseContract {
  connect(runner?: ContractRunner | null): ICodeTrust;
  waitForDeployment(): Promise<this>;

  interface: ICodeTrustInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  isTrustedCode: TypedContractMethod<
    [trustedCode: AddressLike, by: AddressLike, extTimestamp: BigNumberish],
    [boolean],
    "view"
  >;

  trustCodeAt: TypedContractMethod<
    [trustedCode: AddressLike, duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  untrustCodeAt: TypedContractMethod<
    [trustedCode: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "isTrustedCode"
  ): TypedContractMethod<
    [trustedCode: AddressLike, by: AddressLike, extTimestamp: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "trustCodeAt"
  ): TypedContractMethod<
    [trustedCode: AddressLike, duration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "untrustCodeAt"
  ): TypedContractMethod<[trustedCode: AddressLike], [void], "nonpayable">;

  filters: {};
}
